name: Exporter CI

on:
  push:
    branches: [ master ]
    paths-ignore: [ 'dashboards/**' ]
  pull_request:
    branches: [ master ]
    paths-ignore: [ 'dashboards/**' ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: ^1.12
      id: go

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: static analysis
      run: make static-checks

    - name: test
      run: make test

    - name: build
      run: make -j4 build-all

    - uses: actions/upload-artifact@v2
      with:
        name: ha_cluster_exporter
        path: build/bin

  obs-commit:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    container: shap/continuous_deliver
    env:
      OBS_USER: ${{ secrets.OBS_USER }}
      OBS_PASS: ${{ secrets.OBS_PASS }}
      OBS_PROJECT: ${{ secrets.OBS_PROJECT }}
      VERSION: ${{ github.sha }}
      REPOSITORY: ${{ github.repository }}
      GITHUB_OAUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: initialize OBS credentials
      run: |
        mkdir -p $HOME/.config/osc
        cp /root/.config/osc/oscrc $HOME/.config/osc
        /scripts/init_osc_creds.sh
    - run: make exporter-obs-commit

  obs-submit-request:
    needs: build
    if: github.event.release
    runs-on: ubuntu-latest
    container: shap/continuous_deliver
    env:
      OBS_USER: ${{ secrets.OBS_USER }}
      OBS_PASS: ${{ secrets.OBS_PASS }}
      OBS_PROJECT: ${{ secrets.OBS_PROJECT }}
      PACKAGE_NAME: prometheus-ha_cluster_exporter
      TARGET_PROJECT: ${{ secrets.OBS_DOWNSTREAM_PROJECT }}
      VERSION: ${{ github.event.release.tag_name }}
      REPOSITORY: ${{ github.repository }}
      GITHUB_OAUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: initialize OBS credentials
        run: |
          mkdir -p $HOME/.config/osc
          cp /root/.config/osc/oscrc $HOME/.config/osc
          /scripts/init_osc_creds.sh
      - run: make exporter-obs-commit
      - run: /scripts/upload.sh

  github-release-assets:
    if: github.event.release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: ha_cluster_exporter
      - uses: AButler/upload-release-assets@v2.0
        with:
          files: 'ha_cluster_exporter-*'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
