name: Exporter CI

on:
  push:
    branches: [ master ]
    paths-ignore:
        - 'dashboards/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
        - 'dashboards/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: ^1.12
      id: go

    - uses: actions/checkout@v2

    - name: static analysis
      run: make static-checks

    - name: test
      run: make test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: ^1.12
      id: go

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: build
      run: make -j4 build-all

    - uses: actions/upload-artifact@v2
      with:
        name: ha_cluster_exporter
        path: build/bin

  obs-delivery:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    container: shap/continuous_deliver
    env:
      OBS_USER: ${{ secrets.OBS_USER }}
      OBS_PASS: ${{ secrets.OBS_PASS }}
      OBS_PROJECT: ${{ secrets.OBS_PROJECT }}
      VERSION: ${{ github.sha }}
      REPOSITORY: ${{ github.repository }}
      GITHUB_OAUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - run: /scripts/init_osc_creds.sh
    - run: make exporter-obs-commit

